DELETE FROM users;
DELETE FROM stalks;
DELETE FROM posts;

INSERT INTO `users`(`user_identifiant`,`isAdmin`, `name`,`lastName`,`mail`,`dob`,`pass` ) VALUES ('AdminHei',true,'Admin', 'Hei', 'admin.hei@hei.yncrea.fr', '2018-11-05', '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`defaultAvatar`,`pass`) VALUES ('Claudeblmb','Claude', 'Balamba', 'claude.balamba@hei.yncrea.fr', '1996-03-25', 'claudeblmb.jpg' ,'$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`defaultAvatar`,`pass` ) VALUES ('Gregoireldcq','Gregoire', 'Leducq', 'gregoire.leducq@hei.yncrea.fr', '1997-12-09','gregoireldcq.jpg' , '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`defaultAvatar`,`pass` ) VALUES ('Benoitmrcr','Benoît', 'Mercier', 'benoit.mercier@hei.yncrea.fr', '1997-01-01','benoitmrcr.jpg' , '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`defaultAvatar`,`pass` ) VALUES ('Xavierlnc','Xavier', 'Lencou', 'xavier.lencou@hei.yncrea.fr', '1997-10-23','xavierlnc.jpg' , '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`pass` ) VALUES ('jeandpt','Jean', 'Dupont', 'jean.dupont@hei.yncrea.fr', '1995-06-21', '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`pass` ) VALUES ('larrybmbl','Larry', 'Bambel', 'larry.bambel@hei.yncrea.fr', '1997-07-15', '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`pass` ) VALUES ('raydfss','Ray', 'Defesse', 'ray.defesse@hei.yncrea.fr', '1996-01-05', '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`pass` ) VALUES ('jeanmrtdsf','Jean', 'Meurdesoif', 'jean.meurtdesoif@hei.yncrea.fr', '1993-04-24', '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');
INSERT INTO `users`(`user_identifiant`,`name`,`lastName`,`mail`,`dob`,`pass` ) VALUES ('gerardmnsf','Gerard', 'Mensoif', 'gerard.mensoif@hei.yncrea.fr', '1998-02-03', '$argon2i$v=19$m=65536,t=5,p=1$1pExvKiY/4q9J1Z/DhUrPcDspbsBWhTiyopvgTaF1bovBYuiqcOUPbrk0g3G/TumpMg/Aff6KduTbP4BhREaXUEq5iU/ZQO3F+WTM4KIP1WxcUzGkQiv/qG0IJQoACtzfwATCkHhoNkflX+r7FqFhye5unFJlbyvFgG3EubEjMI$NOLfzfUeeRtC+LaGC/LvZN4U+n4xXzsdiSO8olXkk6VQzgkJ4HbaTrdCNwbZLSIjkrbBFL4HL3HnzmSqZ0X7/DXJP1XL3aehNQ34X0/UVG0HG8sOmrjGOaCqx+pkIodryWO05qPCMDQIvGATvmyCuEJHU5iPA3JOfGZssoqQKD4');

INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (1,1);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (2,2);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (3,3);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (4,4);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (5,5);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (6,6);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (7,7);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (8,8);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (9,9);
INSERT INTO `stalks`(`user_id`,`user_stalked`) VALUES (10,10);

INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (1,'2018-11-20','08:03:21','Bonjour tout le monde et bienvenue dans notre réseau !');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (2,'2018-11-20','08:04:01','Salut tout le monde');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (3,'2018-11-20','08:06:22','Hello World');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (4,'2018-11-20','08:05:46','Gerard Mensoif a souvent soif');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (5,'2018-11-20','08:02:31','Larry Bambel tu es un sacré bout en train !');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (6,'2018-11-20','08:10:09','HEI vie');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (7,'2018-11-20','08:25:43','Salut');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (8,'2018-11-20','08:43:54','Bonjour tout le monde');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (9,'2018-11-20','08:13:56','Ce réseau est incroyable ...');
INSERT INTO `posts`(`user_id`,`date_of_post`,`time_of_post`,`texte`) VALUES (10,'2018-11-20','08:54:10','Go sur Twitter tout le monde');